"use strict";
var Card = (function () {
    function Card(Id, Name, Text, Flavor, Artist, Attack, Health, Cost, Rarity, CardClass, Collectible, Elite, Faction, Mechanics, Set, Type) {
        this.Id = Id;
        this.Name = Name;
        this.Text = Text;
        this.Flavor = Flavor;
        this.Artist = Artist;
        this.Attack = Attack;
        this.Health = Health;
        this.Cost = Cost;
        this.Rarity = Rarity;
        this.CardClass = CardClass;
        this.Collectible = Collectible;
        this.Elite = Elite;
        this.Faction = Faction;
        this.Mechanics = Mechanics;
        this.Set = Set;
        this.Type = Type;
    }
    return Card;
}());
exports.Card = Card;
var BlockType;
(function (BlockType) {
    BlockType[BlockType["ATTACK"] = 1] = "ATTACK";
    BlockType[BlockType["JOUST"] = 2] = "JOUST";
    BlockType[BlockType["CONTINUOUS"] = 2] = "CONTINUOUS";
    BlockType[BlockType["POWER"] = 3] = "POWER";
    BlockType[BlockType["SCRIPT"] = 4] = "SCRIPT";
    BlockType[BlockType["TRIGGER"] = 5] = "TRIGGER";
    BlockType[BlockType["DEATHS"] = 6] = "DEATHS";
    BlockType[BlockType["PLAY"] = 7] = "PLAY";
    BlockType[BlockType["FATIGUE"] = 8] = "FATIGUE";
    BlockType[BlockType["RITUAL"] = 9] = "RITUAL";
    BlockType[BlockType["ACTION"] = 99] = "ACTION";
})(BlockType || (BlockType = {}));
var BnetGameType;
(function (BnetGameType) {
    BnetGameType[BnetGameType["BGT_UNKNOWN"] = 0] = "BGT_UNKNOWN";
    BnetGameType[BnetGameType["BGT_FRIENDS"] = 1] = "BGT_FRIENDS";
    BnetGameType[BnetGameType["BGT_RANKED_STANDARD"] = 2] = "BGT_RANKED_STANDARD";
    BnetGameType[BnetGameType["BGT_ARENA"] = 3] = "BGT_ARENA";
    BnetGameType[BnetGameType["BGT_VS_AI"] = 4] = "BGT_VS_AI";
    BnetGameType[BnetGameType["BGT_TUTORIAL"] = 5] = "BGT_TUTORIAL";
    BnetGameType[BnetGameType["BGT_ASYNC"] = 6] = "BGT_ASYNC";
    BnetGameType[BnetGameType["BGT_CASUAL_STANDARD"] = 7] = "BGT_CASUAL_STANDARD";
    BnetGameType[BnetGameType["BGT_TEST1"] = 8] = "BGT_TEST1";
    BnetGameType[BnetGameType["BGT_TEST2"] = 9] = "BGT_TEST2";
    BnetGameType[BnetGameType["BGT_NEWBIE"] = 9] = "BGT_NEWBIE";
    BnetGameType[BnetGameType["BGT_TEST3"] = 10] = "BGT_TEST3";
    BnetGameType[BnetGameType["BGT_TAVERNBRAWL_PVP"] = 16] = "BGT_TAVERNBRAWL_PVP";
    BnetGameType[BnetGameType["BGT_TAVERNBRAWL_1P_VERSUS_AI"] = 17] = "BGT_TAVERNBRAWL_1P_VERSUS_AI";
    BnetGameType[BnetGameType["BGT_TAVERNBRAWL_2P_COOP"] = 18] = "BGT_TAVERNBRAWL_2P_COOP";
    BnetGameType[BnetGameType["BGT_RANKED_WILD"] = 30] = "BGT_RANKED_WILD";
    BnetGameType[BnetGameType["BGT_CASUAL_WILD"] = 31] = "BGT_CASUAL_WILD";
    BnetGameType[BnetGameType["BGT_LAST"] = 32] = "BGT_LAST";
})(BnetGameType || (BnetGameType = {}));
var BnetRegion;
(function (BnetRegion) {
    BnetRegion[BnetRegion["REGION_UNINITIALIZED"] = -1] = "REGION_UNINITIALIZED";
    BnetRegion[BnetRegion["REGION_UNKNOWN"] = 0] = "REGION_UNKNOWN";
    BnetRegion[BnetRegion["REGION_US"] = 1] = "REGION_US";
    BnetRegion[BnetRegion["REGION_EU"] = 2] = "REGION_EU";
    BnetRegion[BnetRegion["REGION_KR"] = 3] = "REGION_KR";
    BnetRegion[BnetRegion["REGION_TW"] = 4] = "REGION_TW";
    BnetRegion[BnetRegion["REGION_CN"] = 5] = "REGION_CN";
    BnetRegion[BnetRegion["REGION_LIVE_VERIFICATION"] = 40] = "REGION_LIVE_VERIFICATION";
    BnetRegion[BnetRegion["REGION_PTR_LOC"] = 41] = "REGION_PTR_LOC";
    BnetRegion[BnetRegion["REGION_MSCHWEITZER_BN11"] = 52] = "REGION_MSCHWEITZER_BN11";
    BnetRegion[BnetRegion["REGION_MSCHWEITZER_BN12"] = 53] = "REGION_MSCHWEITZER_BN12";
    BnetRegion[BnetRegion["REGION_DEV"] = 60] = "REGION_DEV";
    BnetRegion[BnetRegion["REGION_PTR"] = 98] = "REGION_PTR";
})(BnetRegion || (BnetRegion = {}));
var Booster;
(function (Booster) {
    Booster[Booster["INVALID"] = 0] = "INVALID";
    Booster[Booster["CLASSIC"] = 1] = "CLASSIC";
    Booster[Booster["GOBLINS_VS_GNOMES"] = 9] = "GOBLINS_VS_GNOMES";
    Booster[Booster["THE_GRAND_TOURNAMENT"] = 10] = "THE_GRAND_TOURNAMENT";
    Booster[Booster["OLD_GODS"] = 11] = "OLD_GODS";
    Booster[Booster["FIRST_PURCHASE"] = 17] = "FIRST_PURCHASE";
    Booster[Booster["SIGNUP_INCENTIVE"] = 18] = "SIGNUP_INCENTIVE";
    Booster[Booster["MEAN_STREETS"] = 19] = "MEAN_STREETS";
    Booster[Booster["UNGORO"] = 20] = "UNGORO";
})(Booster || (Booster = {}));
var CardClass;
(function (CardClass) {
    CardClass[CardClass["INVALID"] = 0] = "INVALID";
    CardClass[CardClass["DEATHKNIGHT"] = 1] = "DEATHKNIGHT";
    CardClass[CardClass["DRUID"] = 2] = "DRUID";
    CardClass[CardClass["HUNTER"] = 3] = "HUNTER";
    CardClass[CardClass["MAGE"] = 4] = "MAGE";
    CardClass[CardClass["PALADIN"] = 5] = "PALADIN";
    CardClass[CardClass["PRIEST"] = 6] = "PRIEST";
    CardClass[CardClass["ROGUE"] = 7] = "ROGUE";
    CardClass[CardClass["SHAMAN"] = 8] = "SHAMAN";
    CardClass[CardClass["WARLOCK"] = 9] = "WARLOCK";
    CardClass[CardClass["WARRIOR"] = 10] = "WARRIOR";
    CardClass[CardClass["DREAM"] = 11] = "DREAM";
    CardClass[CardClass["NEUTRAL"] = 12] = "NEUTRAL";
})(CardClass || (CardClass = {}));
var CardSet;
(function (CardSet) {
    CardSet[CardSet["INVALID"] = 0] = "INVALID";
    CardSet[CardSet["TEST_TEMPORARY"] = 1] = "TEST_TEMPORARY";
    CardSet[CardSet["CORE"] = 2] = "CORE";
    CardSet[CardSet["EXPERT1"] = 3] = "EXPERT1";
    CardSet[CardSet["REWARD"] = 4] = "REWARD";
    CardSet[CardSet["MISSIONS"] = 5] = "MISSIONS";
    CardSet[CardSet["DEMO"] = 6] = "DEMO";
    CardSet[CardSet["NONE"] = 7] = "NONE";
    CardSet[CardSet["CHEAT"] = 8] = "CHEAT";
    CardSet[CardSet["BLANK"] = 9] = "BLANK";
    CardSet[CardSet["DEBUG_SP"] = 10] = "DEBUG_SP";
    CardSet[CardSet["PROMO"] = 11] = "PROMO";
    CardSet[CardSet["NAXX"] = 12] = "NAXX";
    CardSet[CardSet["FP1"] = 12] = "FP1";
    CardSet[CardSet["PE1"] = 13] = "PE1";
    CardSet[CardSet["GVG"] = 13] = "GVG";
    CardSet[CardSet["BRM"] = 14] = "BRM";
    CardSet[CardSet["FP2"] = 14] = "FP2";
    CardSet[CardSet["PE2"] = 15] = "PE2";
    CardSet[CardSet["TEMP1"] = 15] = "TEMP1";
    CardSet[CardSet["TGT"] = 15] = "TGT";
    CardSet[CardSet["CREDITS"] = 16] = "CREDITS";
    CardSet[CardSet["HERO_SKINS"] = 17] = "HERO_SKINS";
    CardSet[CardSet["TB"] = 18] = "TB";
    CardSet[CardSet["SLUSH"] = 19] = "SLUSH";
    CardSet[CardSet["LOE"] = 20] = "LOE";
    CardSet[CardSet["OG"] = 21] = "OG";
    CardSet[CardSet["OG_RESERVE"] = 22] = "OG_RESERVE";
    CardSet[CardSet["KARA"] = 23] = "KARA";
    CardSet[CardSet["KARA_RESERVE"] = 24] = "KARA_RESERVE";
    CardSet[CardSet["GANGS"] = 25] = "GANGS";
    CardSet[CardSet["GANGS_RESERVE"] = 26] = "GANGS_RESERVE";
    CardSet[CardSet["UNGORO"] = 27] = "UNGORO";
})(CardSet = exports.CardSet || (exports.CardSet = {}));
var CardType;
(function (CardType) {
    CardType[CardType["INVALID"] = 0] = "INVALID";
    CardType[CardType["GAME"] = 1] = "GAME";
    CardType[CardType["PLAYER"] = 2] = "PLAYER";
    CardType[CardType["HERO"] = 3] = "HERO";
    CardType[CardType["MINION"] = 4] = "MINION";
    CardType[CardType["ABILITY"] = 5] = "ABILITY";
    CardType[CardType["SPELL"] = 5] = "SPELL";
    CardType[CardType["ENCHANTMENT"] = 6] = "ENCHANTMENT";
    CardType[CardType["WEAPON"] = 7] = "WEAPON";
    CardType[CardType["ITEM"] = 8] = "ITEM";
    CardType[CardType["TOKEN"] = 9] = "TOKEN";
    CardType[CardType["HERO_POWER"] = 10] = "HERO_POWER";
})(CardType = exports.CardType || (exports.CardType = {}));
var ChoiceType;
(function (ChoiceType) {
    ChoiceType[ChoiceType["INVALID"] = 0] = "INVALID";
    ChoiceType[ChoiceType["MULLIGAN"] = 1] = "MULLIGAN";
    ChoiceType[ChoiceType["GENERAL"] = 2] = "GENERAL";
})(ChoiceType || (ChoiceType = {}));
var DeckType;
(function (DeckType) {
    DeckType[DeckType["NORMAL_DECK"] = 1] = "NORMAL_DECK";
    DeckType[DeckType["AI_DECK"] = 2] = "AI_DECK";
    DeckType[DeckType["DRAFT_DECK"] = 4] = "DRAFT_DECK";
    DeckType[DeckType["PRECON_DECK"] = 5] = "PRECON_DECK";
    DeckType[DeckType["TAVERN_BRAWL_DECK"] = 6] = "TAVERN_BRAWL_DECK";
    DeckType[DeckType["HIDDEN_DECK"] = 1000] = "HIDDEN_DECK";
})(DeckType || (DeckType = {}));
var EnchantmentVisual;
(function (EnchantmentVisual) {
    EnchantmentVisual[EnchantmentVisual["INVALID"] = 0] = "INVALID";
    EnchantmentVisual[EnchantmentVisual["POSITIVE"] = 1] = "POSITIVE";
    EnchantmentVisual[EnchantmentVisual["NEGATIVE"] = 2] = "NEGATIVE";
    EnchantmentVisual[EnchantmentVisual["NEUTRAL"] = 3] = "NEUTRAL";
})(EnchantmentVisual || (EnchantmentVisual = {}));
var Faction;
(function (Faction) {
    Faction[Faction["INVALID"] = 0] = "INVALID";
    Faction[Faction["HORDE"] = 1] = "HORDE";
    Faction[Faction["ALLIANCE"] = 2] = "ALLIANCE";
    Faction[Faction["NEUTRAL"] = 3] = "NEUTRAL";
})(Faction || (Faction = {}));
var FormatType;
(function (FormatType) {
    FormatType[FormatType["FT_UNKNOWN"] = 0] = "FT_UNKNOWN";
    FormatType[FormatType["FT_WILD"] = 1] = "FT_WILD";
    FormatType[FormatType["FT_STANDARD"] = 2] = "FT_STANDARD";
})(FormatType || (FormatType = {}));
var GameTag;
(function (GameTag) {
    GameTag[GameTag["IGNORE_DAMAGE"] = 1] = "IGNORE_DAMAGE";
    GameTag[GameTag["TAG_SCRIPT_DATA_NUM_1"] = 2] = "TAG_SCRIPT_DATA_NUM_1";
    GameTag[GameTag["TAG_SCRIPT_DATA_NUM_2"] = 3] = "TAG_SCRIPT_DATA_NUM_2";
    GameTag[GameTag["TAG_SCRIPT_DATA_ENT_1"] = 4] = "TAG_SCRIPT_DATA_ENT_1";
    GameTag[GameTag["TAG_SCRIPT_DATA_ENT_2"] = 5] = "TAG_SCRIPT_DATA_ENT_2";
    GameTag[GameTag["MISSION_EVENT"] = 6] = "MISSION_EVENT";
    GameTag[GameTag["TIMEOUT"] = 7] = "TIMEOUT";
    GameTag[GameTag["TURN_START"] = 8] = "TURN_START";
    GameTag[GameTag["TURN_TIMER_SLUSH"] = 9] = "TURN_TIMER_SLUSH";
    GameTag[GameTag["PREMIUM"] = 12] = "PREMIUM";
    GameTag[GameTag["GOLD_REWARD_STATE"] = 13] = "GOLD_REWARD_STATE";
    GameTag[GameTag["PLAYSTATE"] = 17] = "PLAYSTATE";
    GameTag[GameTag["LAST_AFFECTED_BY"] = 18] = "LAST_AFFECTED_BY";
    GameTag[GameTag["STEP"] = 19] = "STEP";
    GameTag[GameTag["TURN"] = 20] = "TURN";
    GameTag[GameTag["FATIGUE"] = 22] = "FATIGUE";
    GameTag[GameTag["CURRENT_PLAYER"] = 23] = "CURRENT_PLAYER";
    GameTag[GameTag["FIRST_PLAYER"] = 24] = "FIRST_PLAYER";
    GameTag[GameTag["RESOURCES_USED"] = 25] = "RESOURCES_USED";
    GameTag[GameTag["RESOURCES"] = 26] = "RESOURCES";
    GameTag[GameTag["HERO_ENTITY"] = 27] = "HERO_ENTITY";
    GameTag[GameTag["MAXHANDSIZE"] = 28] = "MAXHANDSIZE";
    GameTag[GameTag["STARTHANDSIZE"] = 29] = "STARTHANDSIZE";
    GameTag[GameTag["PLAYER_ID"] = 30] = "PLAYER_ID";
    GameTag[GameTag["TEAM_ID"] = 31] = "TEAM_ID";
    GameTag[GameTag["TRIGGER_VISUAL"] = 32] = "TRIGGER_VISUAL";
    GameTag[GameTag["RECENTLY_ARRIVED"] = 33] = "RECENTLY_ARRIVED";
    GameTag[GameTag["PROTECTED"] = 34] = "PROTECTED";
    GameTag[GameTag["PROTECTING"] = 35] = "PROTECTING";
    GameTag[GameTag["DEFENDING"] = 36] = "DEFENDING";
    GameTag[GameTag["PROPOSED_DEFENDER"] = 37] = "PROPOSED_DEFENDER";
    GameTag[GameTag["ATTACKING"] = 38] = "ATTACKING";
    GameTag[GameTag["PROPOSED_ATTACKER"] = 39] = "PROPOSED_ATTACKER";
    GameTag[GameTag["ATTACHED"] = 40] = "ATTACHED";
    GameTag[GameTag["EXHAUSTED"] = 43] = "EXHAUSTED";
    GameTag[GameTag["DAMAGE"] = 44] = "DAMAGE";
    GameTag[GameTag["HEALTH"] = 45] = "HEALTH";
    GameTag[GameTag["ATK"] = 47] = "ATK";
    GameTag[GameTag["COST"] = 48] = "COST";
    GameTag[GameTag["ZONE"] = 49] = "ZONE";
    GameTag[GameTag["CONTROLLER"] = 50] = "CONTROLLER";
    GameTag[GameTag["OWNER"] = 51] = "OWNER";
    GameTag[GameTag["DEFINITION"] = 52] = "DEFINITION";
    GameTag[GameTag["ENTITY_ID"] = 53] = "ENTITY_ID";
    GameTag[GameTag["HISTORY_PROXY"] = 54] = "HISTORY_PROXY";
    GameTag[GameTag["COPY_DEATHRATTLE"] = 55] = "COPY_DEATHRATTLE";
    GameTag[GameTag["COPY_DEATHRATTLE_INDEX"] = 56] = "COPY_DEATHRATTLE_INDEX";
    GameTag[GameTag["ELITE"] = 114] = "ELITE";
    GameTag[GameTag["MAXRESOURCES"] = 176] = "MAXRESOURCES";
    GameTag[GameTag["CARD_SET"] = 183] = "CARD_SET";
    GameTag[GameTag["CARDTEXT_INHAND"] = 184] = "CARDTEXT_INHAND";
    GameTag[GameTag["CARDNAME"] = 185] = "CARDNAME";
    GameTag[GameTag["CARD_ID"] = 186] = "CARD_ID";
    GameTag[GameTag["DURABILITY"] = 187] = "DURABILITY";
    GameTag[GameTag["SILENCED"] = 188] = "SILENCED";
    GameTag[GameTag["WINDFURY"] = 189] = "WINDFURY";
    GameTag[GameTag["TAUNT"] = 190] = "TAUNT";
    GameTag[GameTag["STEALTH"] = 191] = "STEALTH";
    GameTag[GameTag["SPELLPOWER"] = 192] = "SPELLPOWER";
    GameTag[GameTag["DIVINE_SHIELD"] = 194] = "DIVINE_SHIELD";
    GameTag[GameTag["CHARGE"] = 197] = "CHARGE";
    GameTag[GameTag["NEXT_STEP"] = 198] = "NEXT_STEP";
    GameTag[GameTag["CLASS"] = 199] = "CLASS";
    GameTag[GameTag["CARDRACE"] = 200] = "CARDRACE";
    GameTag[GameTag["FACTION"] = 201] = "FACTION";
    GameTag[GameTag["CARDTYPE"] = 202] = "CARDTYPE";
    GameTag[GameTag["RARITY"] = 203] = "RARITY";
    GameTag[GameTag["STATE"] = 204] = "STATE";
    GameTag[GameTag["SUMMONED"] = 205] = "SUMMONED";
    GameTag[GameTag["FREEZE"] = 208] = "FREEZE";
    GameTag[GameTag["ENRAGED"] = 212] = "ENRAGED";
    GameTag[GameTag["RECALL"] = 215] = "RECALL";
    GameTag[GameTag["OVERLOAD"] = 215] = "OVERLOAD";
    GameTag[GameTag["LOYALTY"] = 216] = "LOYALTY";
    GameTag[GameTag["DEATHRATTLE"] = 217] = "DEATHRATTLE";
    GameTag[GameTag["DEATH_RATTLE"] = 217] = "DEATH_RATTLE";
    GameTag[GameTag["BATTLECRY"] = 218] = "BATTLECRY";
    GameTag[GameTag["SECRET"] = 219] = "SECRET";
    GameTag[GameTag["COMBO"] = 220] = "COMBO";
    GameTag[GameTag["CANT_HEAL"] = 221] = "CANT_HEAL";
    GameTag[GameTag["CANT_DAMAGE"] = 222] = "CANT_DAMAGE";
    GameTag[GameTag["CANT_SET_ASIDE"] = 223] = "CANT_SET_ASIDE";
    GameTag[GameTag["CANT_REMOVE_FROM_GAME"] = 224] = "CANT_REMOVE_FROM_GAME";
    GameTag[GameTag["CANT_READY"] = 225] = "CANT_READY";
    GameTag[GameTag["CANT_EXHAUST"] = 226] = "CANT_EXHAUST";
    GameTag[GameTag["CANT_ATTACK"] = 227] = "CANT_ATTACK";
    GameTag[GameTag["CANT_TARGET"] = 228] = "CANT_TARGET";
    GameTag[GameTag["CANT_DESTROY"] = 229] = "CANT_DESTROY";
    GameTag[GameTag["CANT_DISCARD"] = 230] = "CANT_DISCARD";
    GameTag[GameTag["CANT_PLAY"] = 231] = "CANT_PLAY";
    GameTag[GameTag["CANT_DRAW"] = 232] = "CANT_DRAW";
    GameTag[GameTag["INCOMING_HEALING_MULTIPLIER"] = 233] = "INCOMING_HEALING_MULTIPLIER";
    GameTag[GameTag["INCOMING_HEALING_ADJUSTMENT"] = 234] = "INCOMING_HEALING_ADJUSTMENT";
    GameTag[GameTag["INCOMING_HEALING_CAP"] = 235] = "INCOMING_HEALING_CAP";
    GameTag[GameTag["INCOMING_DAMAGE_MULTIPLIER"] = 236] = "INCOMING_DAMAGE_MULTIPLIER";
    GameTag[GameTag["INCOMING_DAMAGE_ADJUSTMENT"] = 237] = "INCOMING_DAMAGE_ADJUSTMENT";
    GameTag[GameTag["INCOMING_DAMAGE_CAP"] = 238] = "INCOMING_DAMAGE_CAP";
    GameTag[GameTag["CANT_BE_HEALED"] = 239] = "CANT_BE_HEALED";
    GameTag[GameTag["IMMUNE"] = 240] = "IMMUNE";
    GameTag[GameTag["CANT_BE_DAMAGED"] = 240] = "CANT_BE_DAMAGED";
    GameTag[GameTag["CANT_BE_SET_ASIDE"] = 241] = "CANT_BE_SET_ASIDE";
    GameTag[GameTag["CANT_BE_REMOVED_FROM_GAME"] = 242] = "CANT_BE_REMOVED_FROM_GAME";
    GameTag[GameTag["CANT_BE_READIED"] = 243] = "CANT_BE_READIED";
    GameTag[GameTag["CANT_BE_EXHAUSTED"] = 244] = "CANT_BE_EXHAUSTED";
    GameTag[GameTag["CANT_BE_ATTACKED"] = 245] = "CANT_BE_ATTACKED";
    GameTag[GameTag["CANT_BE_TARGETED"] = 246] = "CANT_BE_TARGETED";
    GameTag[GameTag["CANT_BE_DESTROYED"] = 247] = "CANT_BE_DESTROYED";
    GameTag[GameTag["AttackVisualType"] = 251] = "AttackVisualType";
    GameTag[GameTag["CardTextInPlay"] = 252] = "CardTextInPlay";
    GameTag[GameTag["CANT_BE_SUMMONING_SICK"] = 253] = "CANT_BE_SUMMONING_SICK";
    GameTag[GameTag["FROZEN"] = 260] = "FROZEN";
    GameTag[GameTag["JUST_PLAYED"] = 261] = "JUST_PLAYED";
    GameTag[GameTag["LINKED_ENTITY"] = 262] = "LINKED_ENTITY";
    GameTag[GameTag["LINKEDCARD"] = 262] = "LINKEDCARD";
    GameTag[GameTag["ZONE_POSITION"] = 263] = "ZONE_POSITION";
    GameTag[GameTag["CANT_BE_FROZEN"] = 264] = "CANT_BE_FROZEN";
    GameTag[GameTag["COMBO_ACTIVE"] = 266] = "COMBO_ACTIVE";
    GameTag[GameTag["CARD_TARGET"] = 267] = "CARD_TARGET";
    GameTag[GameTag["DevState"] = 268] = "DevState";
    GameTag[GameTag["NUM_CARDS_PLAYED_THIS_TURN"] = 269] = "NUM_CARDS_PLAYED_THIS_TURN";
    GameTag[GameTag["CANT_BE_TARGETED_BY_OPPONENTS"] = 270] = "CANT_BE_TARGETED_BY_OPPONENTS";
    GameTag[GameTag["NUM_TURNS_IN_PLAY"] = 271] = "NUM_TURNS_IN_PLAY";
    GameTag[GameTag["NUM_TURNS_LEFT"] = 272] = "NUM_TURNS_LEFT";
    GameTag[GameTag["OUTGOING_DAMAGE_CAP"] = 273] = "OUTGOING_DAMAGE_CAP";
    GameTag[GameTag["OUTGOING_DAMAGE_ADJUSTMENT"] = 274] = "OUTGOING_DAMAGE_ADJUSTMENT";
    GameTag[GameTag["OUTGOING_DAMAGE_MULTIPLIER"] = 275] = "OUTGOING_DAMAGE_MULTIPLIER";
    GameTag[GameTag["OUTGOING_HEALING_CAP"] = 276] = "OUTGOING_HEALING_CAP";
    GameTag[GameTag["OUTGOING_HEALING_ADJUSTMENT"] = 277] = "OUTGOING_HEALING_ADJUSTMENT";
    GameTag[GameTag["OUTGOING_HEALING_MULTIPLIER"] = 278] = "OUTGOING_HEALING_MULTIPLIER";
    GameTag[GameTag["INCOMING_ABILITY_DAMAGE_ADJUSTMENT"] = 279] = "INCOMING_ABILITY_DAMAGE_ADJUSTMENT";
    GameTag[GameTag["INCOMING_COMBAT_DAMAGE_ADJUSTMENT"] = 280] = "INCOMING_COMBAT_DAMAGE_ADJUSTMENT";
    GameTag[GameTag["OUTGOING_ABILITY_DAMAGE_ADJUSTMENT"] = 281] = "OUTGOING_ABILITY_DAMAGE_ADJUSTMENT";
    GameTag[GameTag["OUTGOING_COMBAT_DAMAGE_ADJUSTMENT"] = 282] = "OUTGOING_COMBAT_DAMAGE_ADJUSTMENT";
    GameTag[GameTag["OUTGOING_ABILITY_DAMAGE_MULTIPLIER"] = 283] = "OUTGOING_ABILITY_DAMAGE_MULTIPLIER";
    GameTag[GameTag["OUTGOING_ABILITY_DAMAGE_CAP"] = 284] = "OUTGOING_ABILITY_DAMAGE_CAP";
    GameTag[GameTag["INCOMING_ABILITY_DAMAGE_MULTIPLIER"] = 285] = "INCOMING_ABILITY_DAMAGE_MULTIPLIER";
    GameTag[GameTag["INCOMING_ABILITY_DAMAGE_CAP"] = 286] = "INCOMING_ABILITY_DAMAGE_CAP";
    GameTag[GameTag["OUTGOING_COMBAT_DAMAGE_MULTIPLIER"] = 287] = "OUTGOING_COMBAT_DAMAGE_MULTIPLIER";
    GameTag[GameTag["OUTGOING_COMBAT_DAMAGE_CAP"] = 288] = "OUTGOING_COMBAT_DAMAGE_CAP";
    GameTag[GameTag["INCOMING_COMBAT_DAMAGE_MULTIPLIER"] = 289] = "INCOMING_COMBAT_DAMAGE_MULTIPLIER";
    GameTag[GameTag["INCOMING_COMBAT_DAMAGE_CAP"] = 290] = "INCOMING_COMBAT_DAMAGE_CAP";
    GameTag[GameTag["CURRENT_SPELLPOWER"] = 291] = "CURRENT_SPELLPOWER";
    GameTag[GameTag["ARMOR"] = 292] = "ARMOR";
    GameTag[GameTag["MORPH"] = 293] = "MORPH";
    GameTag[GameTag["IS_MORPHED"] = 294] = "IS_MORPHED";
    GameTag[GameTag["TEMP_RESOURCES"] = 295] = "TEMP_RESOURCES";
    GameTag[GameTag["OVERLOAD_OWED"] = 296] = "OVERLOAD_OWED";
    GameTag[GameTag["RECALL_OWED"] = 296] = "RECALL_OWED";
    GameTag[GameTag["NUM_ATTACKS_THIS_TURN"] = 297] = "NUM_ATTACKS_THIS_TURN";
    GameTag[GameTag["NEXT_ALLY_BUFF"] = 302] = "NEXT_ALLY_BUFF";
    GameTag[GameTag["MAGNET"] = 303] = "MAGNET";
    GameTag[GameTag["FIRST_CARD_PLAYED_THIS_TURN"] = 304] = "FIRST_CARD_PLAYED_THIS_TURN";
    GameTag[GameTag["MULLIGAN_STATE"] = 305] = "MULLIGAN_STATE";
    GameTag[GameTag["TAUNT_READY"] = 306] = "TAUNT_READY";
    GameTag[GameTag["STEALTH_READY"] = 307] = "STEALTH_READY";
    GameTag[GameTag["CHARGE_READY"] = 308] = "CHARGE_READY";
    GameTag[GameTag["CANT_BE_TARGETED_BY_ABILITIES"] = 311] = "CANT_BE_TARGETED_BY_ABILITIES";
    GameTag[GameTag["CANT_BE_TARGETED_BY_SPELLS"] = 311] = "CANT_BE_TARGETED_BY_SPELLS";
    GameTag[GameTag["SHOULDEXITCOMBAT"] = 312] = "SHOULDEXITCOMBAT";
    GameTag[GameTag["CREATOR"] = 313] = "CREATOR";
    GameTag[GameTag["CANT_BE_DISPELLED"] = 314] = "CANT_BE_DISPELLED";
    GameTag[GameTag["CANT_BE_SILENCED"] = 314] = "CANT_BE_SILENCED";
    GameTag[GameTag["DIVINE_SHIELD_READY"] = 314] = "DIVINE_SHIELD_READY";
    GameTag[GameTag["PARENT_CARD"] = 316] = "PARENT_CARD";
    GameTag[GameTag["NUM_MINIONS_PLAYED_THIS_TURN"] = 317] = "NUM_MINIONS_PLAYED_THIS_TURN";
    GameTag[GameTag["PREDAMAGE"] = 318] = "PREDAMAGE";
    GameTag[GameTag["COLLECTIBLE"] = 321] = "COLLECTIBLE";
    GameTag[GameTag["TARGETING_ARROW_TEXT"] = 325] = "TARGETING_ARROW_TEXT";
    GameTag[GameTag["ENCHANTMENT_BIRTH_VISUAL"] = 330] = "ENCHANTMENT_BIRTH_VISUAL";
    GameTag[GameTag["ENCHANTMENT_IDLE_VISUAL"] = 331] = "ENCHANTMENT_IDLE_VISUAL";
    GameTag[GameTag["CANT_BE_TARGETED_BY_HERO_POWERS"] = 332] = "CANT_BE_TARGETED_BY_HERO_POWERS";
    GameTag[GameTag["WEAPON"] = 334] = "WEAPON";
    GameTag[GameTag["InvisibleDeathrattle"] = 335] = "InvisibleDeathrattle";
    GameTag[GameTag["HEALTH_MINIMUM"] = 337] = "HEALTH_MINIMUM";
    GameTag[GameTag["TAG_ONE_TURN_EFFECT"] = 338] = "TAG_ONE_TURN_EFFECT";
    GameTag[GameTag["SILENCE"] = 339] = "SILENCE";
    GameTag[GameTag["COUNTER"] = 340] = "COUNTER";
    GameTag[GameTag["ARTISTNAME"] = 342] = "ARTISTNAME";
    GameTag[GameTag["LocalizationNotes"] = 344] = "LocalizationNotes";
    GameTag[GameTag["HAND_REVEALED"] = 348] = "HAND_REVEALED";
    GameTag[GameTag["ImmuneToSpellpower"] = 349] = "ImmuneToSpellpower";
    GameTag[GameTag["ADJACENT_BUFF"] = 350] = "ADJACENT_BUFF";
    GameTag[GameTag["FLAVORTEXT"] = 351] = "FLAVORTEXT";
    GameTag[GameTag["FORCED_PLAY"] = 352] = "FORCED_PLAY";
    GameTag[GameTag["LOW_HEALTH_THRESHOLD"] = 353] = "LOW_HEALTH_THRESHOLD";
    GameTag[GameTag["IGNORE_DAMAGE_OFF"] = 354] = "IGNORE_DAMAGE_OFF";
    GameTag[GameTag["GrantCharge"] = 355] = "GrantCharge";
    GameTag[GameTag["SPELLPOWER_DOUBLE"] = 356] = "SPELLPOWER_DOUBLE";
    GameTag[GameTag["HEALING_DOUBLE"] = 357] = "HEALING_DOUBLE";
    GameTag[GameTag["NUM_OPTIONS_PLAYED_THIS_TURN"] = 358] = "NUM_OPTIONS_PLAYED_THIS_TURN";
    GameTag[GameTag["NUM_OPTIONS"] = 359] = "NUM_OPTIONS";
    GameTag[GameTag["TO_BE_DESTROYED"] = 360] = "TO_BE_DESTROYED";
    GameTag[GameTag["HealTarget"] = 361] = "HealTarget";
    GameTag[GameTag["AURA"] = 362] = "AURA";
    GameTag[GameTag["POISONOUS"] = 363] = "POISONOUS";
    GameTag[GameTag["HOW_TO_EARN"] = 364] = "HOW_TO_EARN";
    GameTag[GameTag["HOW_TO_EARN_GOLDEN"] = 365] = "HOW_TO_EARN_GOLDEN";
    GameTag[GameTag["TAG_HERO_POWER_DOUBLE"] = 366] = "TAG_HERO_POWER_DOUBLE";
    GameTag[GameTag["HERO_POWER_DOUBLE"] = 366] = "HERO_POWER_DOUBLE";
    GameTag[GameTag["AI_MUST_PLAY"] = 367] = "AI_MUST_PLAY";
    GameTag[GameTag["TAG_AI_MUST_PLAY"] = 367] = "TAG_AI_MUST_PLAY";
    GameTag[GameTag["NUM_MINIONS_PLAYER_KILLED_THIS_TURN"] = 368] = "NUM_MINIONS_PLAYER_KILLED_THIS_TURN";
    GameTag[GameTag["NUM_MINIONS_KILLED_THIS_TURN"] = 369] = "NUM_MINIONS_KILLED_THIS_TURN";
    GameTag[GameTag["AFFECTED_BY_SPELL_POWER"] = 370] = "AFFECTED_BY_SPELL_POWER";
    GameTag[GameTag["EXTRA_DEATHRATTLES"] = 371] = "EXTRA_DEATHRATTLES";
    GameTag[GameTag["START_WITH_1_HEALTH"] = 372] = "START_WITH_1_HEALTH";
    GameTag[GameTag["IMMUNE_WHILE_ATTACKING"] = 373] = "IMMUNE_WHILE_ATTACKING";
    GameTag[GameTag["MULTIPLY_HERO_DAMAGE"] = 374] = "MULTIPLY_HERO_DAMAGE";
    GameTag[GameTag["MULTIPLY_BUFF_VALUE"] = 375] = "MULTIPLY_BUFF_VALUE";
    GameTag[GameTag["CUSTOM_KEYWORD_EFFECT"] = 376] = "CUSTOM_KEYWORD_EFFECT";
    GameTag[GameTag["TOPDECK"] = 377] = "TOPDECK";
    GameTag[GameTag["CANT_BE_TARGETED_BY_BATTLECRIES"] = 379] = "CANT_BE_TARGETED_BY_BATTLECRIES";
    GameTag[GameTag["OVERKILL"] = 380] = "OVERKILL";
    GameTag[GameTag["SHOWN_HERO_POWER"] = 380] = "SHOWN_HERO_POWER";
    GameTag[GameTag["HERO_POWER"] = 380] = "HERO_POWER";
    GameTag[GameTag["DEATHRATTLE_RETURN_ZONE"] = 382] = "DEATHRATTLE_RETURN_ZONE";
    GameTag[GameTag["DEATHRATTLE_SENDS_BACK_TO_DECK"] = 382] = "DEATHRATTLE_SENDS_BACK_TO_DECK";
    GameTag[GameTag["STEADY_SHOT_CAN_TARGET"] = 383] = "STEADY_SHOT_CAN_TARGET";
    GameTag[GameTag["DISPLAYED_CREATOR"] = 385] = "DISPLAYED_CREATOR";
    GameTag[GameTag["POWERED_UP"] = 386] = "POWERED_UP";
    GameTag[GameTag["SPARE_PART"] = 388] = "SPARE_PART";
    GameTag[GameTag["FORGETFUL"] = 389] = "FORGETFUL";
    GameTag[GameTag["CAN_SUMMON_MAXPLUSONE_MINION"] = 390] = "CAN_SUMMON_MAXPLUSONE_MINION";
    GameTag[GameTag["OBFUSCATED"] = 391] = "OBFUSCATED";
    GameTag[GameTag["BURNING"] = 392] = "BURNING";
    GameTag[GameTag["OVERLOAD_LOCKED"] = 393] = "OVERLOAD_LOCKED";
    GameTag[GameTag["NUM_TIMES_HERO_POWER_USED_THIS_GAME"] = 394] = "NUM_TIMES_HERO_POWER_USED_THIS_GAME";
    GameTag[GameTag["CURRENT_HEROPOWER_DAMAGE_BONUS"] = 395] = "CURRENT_HEROPOWER_DAMAGE_BONUS";
    GameTag[GameTag["HEROPOWER_DAMAGE"] = 396] = "HEROPOWER_DAMAGE";
    GameTag[GameTag["LAST_CARD_PLAYED"] = 397] = "LAST_CARD_PLAYED";
    GameTag[GameTag["NUM_FRIENDLY_MINIONS_THAT_DIED_THIS_TURN"] = 398] = "NUM_FRIENDLY_MINIONS_THAT_DIED_THIS_TURN";
    GameTag[GameTag["NUM_CARDS_DRAWN_THIS_TURN"] = 399] = "NUM_CARDS_DRAWN_THIS_TURN";
    GameTag[GameTag["AI_ONE_SHOT_KILL"] = 400] = "AI_ONE_SHOT_KILL";
    GameTag[GameTag["EVIL_GLOW"] = 401] = "EVIL_GLOW";
    GameTag[GameTag["HIDE_COST"] = 402] = "HIDE_COST";
    GameTag[GameTag["HIDE_STATS"] = 402] = "HIDE_STATS";
    GameTag[GameTag["INSPIRE"] = 403] = "INSPIRE";
    GameTag[GameTag["RECEIVES_DOUBLE_SPELLDAMAGE_BONUS"] = 404] = "RECEIVES_DOUBLE_SPELLDAMAGE_BONUS";
    GameTag[GameTag["HEROPOWER_ADDITIONAL_ACTIVATIONS"] = 405] = "HEROPOWER_ADDITIONAL_ACTIVATIONS";
    GameTag[GameTag["HEROPOWER_ACTIVATIONS_THIS_TURN"] = 406] = "HEROPOWER_ACTIVATIONS_THIS_TURN";
    GameTag[GameTag["REVEALED"] = 410] = "REVEALED";
    GameTag[GameTag["NUM_FRIENDLY_MINIONS_THAT_DIED_THIS_GAME"] = 412] = "NUM_FRIENDLY_MINIONS_THAT_DIED_THIS_GAME";
    GameTag[GameTag["CANNOT_ATTACK_HEROES"] = 413] = "CANNOT_ATTACK_HEROES";
    GameTag[GameTag["LOCK_AND_LOAD"] = 414] = "LOCK_AND_LOAD";
    GameTag[GameTag["TREASURE"] = 415] = "TREASURE";
    GameTag[GameTag["DISCOVER"] = 415] = "DISCOVER";
    GameTag[GameTag["SHADOWFORM"] = 416] = "SHADOWFORM";
    GameTag[GameTag["NUM_FRIENDLY_MINIONS_THAT_ATTACKED_THIS_TURN"] = 417] = "NUM_FRIENDLY_MINIONS_THAT_ATTACKED_THIS_TURN";
    GameTag[GameTag["NUM_RESOURCES_SPENT_THIS_GAME"] = 418] = "NUM_RESOURCES_SPENT_THIS_GAME";
    GameTag[GameTag["CHOOSE_BOTH"] = 419] = "CHOOSE_BOTH";
    GameTag[GameTag["ELECTRIC_CHARGE_LEVEL"] = 420] = "ELECTRIC_CHARGE_LEVEL";
    GameTag[GameTag["HEAVILY_ARMORED"] = 421] = "HEAVILY_ARMORED";
    GameTag[GameTag["DONT_SHOW_IMMUNE"] = 422] = "DONT_SHOW_IMMUNE";
    GameTag[GameTag["RITUAL"] = 424] = "RITUAL";
    GameTag[GameTag["PREHEALING"] = 425] = "PREHEALING";
    GameTag[GameTag["APPEAR_FUNCTIONALLY_DEAD"] = 426] = "APPEAR_FUNCTIONALLY_DEAD";
    GameTag[GameTag["OVERLOAD_THIS_GAME"] = 427] = "OVERLOAD_THIS_GAME";
    GameTag[GameTag["SPELLS_COST_HEALTH"] = 431] = "SPELLS_COST_HEALTH";
    GameTag[GameTag["HISTORY_PROXY_NO_BIG_CARD"] = 432] = "HISTORY_PROXY_NO_BIG_CARD";
    GameTag[GameTag["PROXY_CTHUN"] = 434] = "PROXY_CTHUN";
    GameTag[GameTag["TRANSFORMED_FROM_CARD"] = 435] = "TRANSFORMED_FROM_CARD";
    GameTag[GameTag["CTHUN"] = 436] = "CTHUN";
    GameTag[GameTag["CAST_RANDOM_SPELLS"] = 437] = "CAST_RANDOM_SPELLS";
    GameTag[GameTag["SHIFTING"] = 438] = "SHIFTING";
    GameTag[GameTag["JADE_GOLEM"] = 441] = "JADE_GOLEM";
    GameTag[GameTag["EMBRACE_THE_SHADOW"] = 442] = "EMBRACE_THE_SHADOW";
    GameTag[GameTag["CHOOSE_ONE"] = 443] = "CHOOSE_ONE";
    GameTag[GameTag["EXTRA_ATTACKS_THIS_TURN"] = 444] = "EXTRA_ATTACKS_THIS_TURN";
    GameTag[GameTag["SEEN_CTHUN"] = 445] = "SEEN_CTHUN";
    GameTag[GameTag["MINION_TYPE_REFERENCE"] = 447] = "MINION_TYPE_REFERENCE";
    GameTag[GameTag["UNTOUCHABLE"] = 448] = "UNTOUCHABLE";
    GameTag[GameTag["RED_MANA_CRYSTALS"] = 449] = "RED_MANA_CRYSTALS";
    GameTag[GameTag["SCORE_LABELID_1"] = 450] = "SCORE_LABELID_1";
    GameTag[GameTag["SCORE_VALUE_1"] = 451] = "SCORE_VALUE_1";
    GameTag[GameTag["SCORE_LABELID_2"] = 452] = "SCORE_LABELID_2";
    GameTag[GameTag["SCORE_VALUE_2"] = 453] = "SCORE_VALUE_2";
    GameTag[GameTag["SCORE_LABELID_3"] = 454] = "SCORE_LABELID_3";
    GameTag[GameTag["SCORE_VALUE_3"] = 455] = "SCORE_VALUE_3";
    GameTag[GameTag["CANT_BE_FATIGUED"] = 456] = "CANT_BE_FATIGUED";
    GameTag[GameTag["AUTOATTACK"] = 457] = "AUTOATTACK";
    GameTag[GameTag["ARMS_DEALING"] = 458] = "ARMS_DEALING";
    GameTag[GameTag["TAG_LAST_KNOWN_COST_IN_HAND"] = 466] = "TAG_LAST_KNOWN_COST_IN_HAND";
    GameTag[GameTag["DEFINING_ENCHANTMENT"] = 469] = "DEFINING_ENCHANTMENT";
    GameTag[GameTag["FINISH_ATTACK_SPELL_ON_DAMAGE"] = 470] = "FINISH_ATTACK_SPELL_ON_DAMAGE";
    GameTag[GameTag["KAZAKUS_POTION_POWER_1"] = 471] = "KAZAKUS_POTION_POWER_1";
    GameTag[GameTag["KAZAKUS_POTION_POWER_2"] = 472] = "KAZAKUS_POTION_POWER_2";
    GameTag[GameTag["MODIFY_DEFINITION_ATTACK"] = 473] = "MODIFY_DEFINITION_ATTACK";
    GameTag[GameTag["MODIFY_DEFINITION_HEALTH"] = 474] = "MODIFY_DEFINITION_HEALTH";
    GameTag[GameTag["MODIFY_DEFINITION_COST"] = 475] = "MODIFY_DEFINITION_COST";
    GameTag[GameTag["MULTIPLE_CLASSES"] = 476] = "MULTIPLE_CLASSES";
    GameTag[GameTag["ALL_TARGETS_RANDOM"] = 477] = "ALL_TARGETS_RANDOM";
    GameTag[GameTag["MULTI_CLASS_GROUP"] = 480] = "MULTI_CLASS_GROUP";
    GameTag[GameTag["CARD_COSTS_HEALTH"] = 481] = "CARD_COSTS_HEALTH";
    GameTag[GameTag["GRIMY_GOONS"] = 482] = "GRIMY_GOONS";
    GameTag[GameTag["JADE_LOTUS"] = 483] = "JADE_LOTUS";
    GameTag[GameTag["KABAL"] = 484] = "KABAL";
    GameTag[GameTag["ADDITIONAL_PLAY_REQS_1"] = 515] = "ADDITIONAL_PLAY_REQS_1";
    GameTag[GameTag["ADDITIONAL_PLAY_REQS_2"] = 516] = "ADDITIONAL_PLAY_REQS_2";
    GameTag[GameTag["BOSS"] = 556] = "BOSS";
})(GameTag || (GameTag = {}));
var GameType;
(function (GameType) {
    GameType[GameType["GT_UNKNOWN"] = 0] = "GT_UNKNOWN";
    GameType[GameType["GT_VS_AI"] = 1] = "GT_VS_AI";
    GameType[GameType["GT_VS_FRIEND"] = 2] = "GT_VS_FRIEND";
    GameType[GameType["GT_TUTORIAL"] = 4] = "GT_TUTORIAL";
    GameType[GameType["GT_ARENA"] = 5] = "GT_ARENA";
    GameType[GameType["GT_TEST"] = 6] = "GT_TEST";
    GameType[GameType["GT_RANKED"] = 7] = "GT_RANKED";
    GameType[GameType["GT_CASUAL"] = 8] = "GT_CASUAL";
    GameType[GameType["GT_TAVERNBRAWL"] = 16] = "GT_TAVERNBRAWL";
    GameType[GameType["GT_TB_1P_VS_AI"] = 17] = "GT_TB_1P_VS_AI";
    GameType[GameType["GT_TB_2P_COOP"] = 18] = "GT_TB_2P_COOP";
    GameType[GameType["GT_LAST"] = 19] = "GT_LAST";
})(GameType || (GameType = {}));
var GoldRewardState;
(function (GoldRewardState) {
    GoldRewardState[GoldRewardState["INVALID"] = 0] = "INVALID";
    GoldRewardState[GoldRewardState["ELIGIBLE"] = 1] = "ELIGIBLE";
    GoldRewardState[GoldRewardState["WRONG_GAME_TYPE"] = 2] = "WRONG_GAME_TYPE";
    GoldRewardState[GoldRewardState["ALREADY_CAPPED"] = 3] = "ALREADY_CAPPED";
    GoldRewardState[GoldRewardState["BAD_RATING"] = 4] = "BAD_RATING";
    GoldRewardState[GoldRewardState["SHORT_GAME_BY_TIME"] = 5] = "SHORT_GAME_BY_TIME";
    GoldRewardState[GoldRewardState["SHORT_GAME"] = 5] = "SHORT_GAME";
    GoldRewardState[GoldRewardState["OVER_CAIS"] = 6] = "OVER_CAIS";
})(GoldRewardState || (GoldRewardState = {}));
var Locale;
(function (Locale) {
    Locale[Locale["UNKNOWN"] = -1] = "UNKNOWN";
    Locale[Locale["enUS"] = 0] = "enUS";
    Locale[Locale["enGB"] = 1] = "enGB";
    Locale[Locale["frFR"] = 2] = "frFR";
    Locale[Locale["deDE"] = 3] = "deDE";
    Locale[Locale["koKR"] = 4] = "koKR";
    Locale[Locale["esES"] = 5] = "esES";
    Locale[Locale["esMX"] = 6] = "esMX";
    Locale[Locale["ruRU"] = 7] = "ruRU";
    Locale[Locale["zhTW"] = 8] = "zhTW";
    Locale[Locale["zhCN"] = 9] = "zhCN";
    Locale[Locale["itIT"] = 10] = "itIT";
    Locale[Locale["ptBR"] = 11] = "ptBR";
    Locale[Locale["plPL"] = 12] = "plPL";
    Locale[Locale["ptPT"] = 13] = "ptPT";
    Locale[Locale["jaJP"] = 14] = "jaJP";
    Locale[Locale["thTH"] = 15] = "thTH";
})(Locale || (Locale = {}));
var MetaDataType;
(function (MetaDataType) {
    MetaDataType[MetaDataType["META_TARGET"] = 0] = "META_TARGET";
    MetaDataType[MetaDataType["TARGET"] = 0] = "TARGET";
    MetaDataType[MetaDataType["DAMAGE"] = 1] = "DAMAGE";
    MetaDataType[MetaDataType["META_DAMAGE"] = 1] = "META_DAMAGE";
    MetaDataType[MetaDataType["HEALING"] = 2] = "HEALING";
    MetaDataType[MetaDataType["META_HEALING"] = 2] = "META_HEALING";
    MetaDataType[MetaDataType["JOUST"] = 3] = "JOUST";
    MetaDataType[MetaDataType["CLIENT_HISTORY"] = 4] = "CLIENT_HISTORY";
    MetaDataType[MetaDataType["SHOW_BIG_CARD"] = 5] = "SHOW_BIG_CARD";
    MetaDataType[MetaDataType["EFFECT_TIMING"] = 6] = "EFFECT_TIMING";
    MetaDataType[MetaDataType["HISTORY_TARGET"] = 7] = "HISTORY_TARGET";
    MetaDataType[MetaDataType["OVERRIDE_HISTORY"] = 8] = "OVERRIDE_HISTORY";
})(MetaDataType || (MetaDataType = {}));
var Mulligan;
(function (Mulligan) {
    Mulligan[Mulligan["INVALID"] = 0] = "INVALID";
    Mulligan[Mulligan["INPUT"] = 1] = "INPUT";
    Mulligan[Mulligan["DEALING"] = 2] = "DEALING";
    Mulligan[Mulligan["WAITING"] = 3] = "WAITING";
    Mulligan[Mulligan["DONE"] = 4] = "DONE";
})(Mulligan || (Mulligan = {}));
var MultiClassGroup;
(function (MultiClassGroup) {
    MultiClassGroup[MultiClassGroup["INVALID"] = 0] = "INVALID";
    MultiClassGroup[MultiClassGroup["GRIMY_GOONS"] = 1] = "GRIMY_GOONS";
    MultiClassGroup[MultiClassGroup["JADE_LOTUS"] = 2] = "JADE_LOTUS";
    MultiClassGroup[MultiClassGroup["KABAL"] = 3] = "KABAL";
})(MultiClassGroup || (MultiClassGroup = {}));
var OptionType;
(function (OptionType) {
    OptionType[OptionType["PASS"] = 1] = "PASS";
    OptionType[OptionType["END_TURN"] = 2] = "END_TURN";
    OptionType[OptionType["POWER"] = 3] = "POWER";
})(OptionType || (OptionType = {}));
var PlayReq;
(function (PlayReq) {
    PlayReq[PlayReq["REQ_MINION_TARGET"] = 1] = "REQ_MINION_TARGET";
    PlayReq[PlayReq["REQ_FRIENDLY_TARGET"] = 2] = "REQ_FRIENDLY_TARGET";
    PlayReq[PlayReq["REQ_ENEMY_TARGET"] = 3] = "REQ_ENEMY_TARGET";
    PlayReq[PlayReq["REQ_DAMAGED_TARGET"] = 4] = "REQ_DAMAGED_TARGET";
    PlayReq[PlayReq["REQ_ENCHANTED_TARGET"] = 5] = "REQ_ENCHANTED_TARGET";
    PlayReq[PlayReq["REQ_FROZEN_TARGET"] = 6] = "REQ_FROZEN_TARGET";
    PlayReq[PlayReq["REQ_CHARGE_TARGET"] = 7] = "REQ_CHARGE_TARGET";
    PlayReq[PlayReq["REQ_TARGET_MAX_ATTACK"] = 8] = "REQ_TARGET_MAX_ATTACK";
    PlayReq[PlayReq["REQ_NONSELF_TARGET"] = 9] = "REQ_NONSELF_TARGET";
    PlayReq[PlayReq["REQ_TARGET_WITH_RACE"] = 10] = "REQ_TARGET_WITH_RACE";
    PlayReq[PlayReq["REQ_TARGET_TO_PLAY"] = 11] = "REQ_TARGET_TO_PLAY";
    PlayReq[PlayReq["REQ_NUM_MINION_SLOTS"] = 12] = "REQ_NUM_MINION_SLOTS";
    PlayReq[PlayReq["REQ_WEAPON_EQUIPPED"] = 13] = "REQ_WEAPON_EQUIPPED";
    PlayReq[PlayReq["REQ_ENOUGH_MANA"] = 14] = "REQ_ENOUGH_MANA";
    PlayReq[PlayReq["REQ_YOUR_TURN"] = 15] = "REQ_YOUR_TURN";
    PlayReq[PlayReq["REQ_NONSTEALTH_ENEMY_TARGET"] = 16] = "REQ_NONSTEALTH_ENEMY_TARGET";
    PlayReq[PlayReq["REQ_HERO_TARGET"] = 17] = "REQ_HERO_TARGET";
    PlayReq[PlayReq["REQ_SECRET_CAP"] = 18] = "REQ_SECRET_CAP";
    PlayReq[PlayReq["REQ_MINION_CAP_IF_TARGET_AVAILABLE"] = 19] = "REQ_MINION_CAP_IF_TARGET_AVAILABLE";
    PlayReq[PlayReq["REQ_MINION_CAP"] = 20] = "REQ_MINION_CAP";
    PlayReq[PlayReq["REQ_TARGET_ATTACKED_THIS_TURN"] = 21] = "REQ_TARGET_ATTACKED_THIS_TURN";
    PlayReq[PlayReq["REQ_TARGET_IF_AVAILABLE"] = 22] = "REQ_TARGET_IF_AVAILABLE";
    PlayReq[PlayReq["REQ_MINIMUM_ENEMY_MINIONS"] = 23] = "REQ_MINIMUM_ENEMY_MINIONS";
    PlayReq[PlayReq["REQ_TARGET_FOR_COMBO"] = 24] = "REQ_TARGET_FOR_COMBO";
    PlayReq[PlayReq["REQ_NOT_EXHAUSTED_ACTIVATE"] = 25] = "REQ_NOT_EXHAUSTED_ACTIVATE";
    PlayReq[PlayReq["REQ_UNIQUE_SECRET"] = 26] = "REQ_UNIQUE_SECRET";
    PlayReq[PlayReq["REQ_TARGET_TAUNTER"] = 27] = "REQ_TARGET_TAUNTER";
    PlayReq[PlayReq["REQ_CAN_BE_ATTACKED"] = 28] = "REQ_CAN_BE_ATTACKED";
    PlayReq[PlayReq["REQ_ACTION_PWR_IS_MASTER_PWR"] = 29] = "REQ_ACTION_PWR_IS_MASTER_PWR";
    PlayReq[PlayReq["REQ_TARGET_MAGNET"] = 30] = "REQ_TARGET_MAGNET";
    PlayReq[PlayReq["REQ_ATTACK_GREATER_THAN_0"] = 31] = "REQ_ATTACK_GREATER_THAN_0";
    PlayReq[PlayReq["REQ_ATTACKER_NOT_FROZEN"] = 32] = "REQ_ATTACKER_NOT_FROZEN";
    PlayReq[PlayReq["REQ_HERO_OR_MINION_TARGET"] = 33] = "REQ_HERO_OR_MINION_TARGET";
    PlayReq[PlayReq["REQ_CAN_BE_TARGETED_BY_SPELLS"] = 34] = "REQ_CAN_BE_TARGETED_BY_SPELLS";
    PlayReq[PlayReq["REQ_SUBCARD_IS_PLAYABLE"] = 35] = "REQ_SUBCARD_IS_PLAYABLE";
    PlayReq[PlayReq["REQ_TARGET_FOR_NO_COMBO"] = 36] = "REQ_TARGET_FOR_NO_COMBO";
    PlayReq[PlayReq["REQ_NOT_MINION_JUST_PLAYED"] = 37] = "REQ_NOT_MINION_JUST_PLAYED";
    PlayReq[PlayReq["REQ_NOT_EXHAUSTED_HERO_POWER"] = 38] = "REQ_NOT_EXHAUSTED_HERO_POWER";
    PlayReq[PlayReq["REQ_CAN_BE_TARGETED_BY_OPPONENTS"] = 39] = "REQ_CAN_BE_TARGETED_BY_OPPONENTS";
    PlayReq[PlayReq["REQ_ATTACKER_CAN_ATTACK"] = 40] = "REQ_ATTACKER_CAN_ATTACK";
    PlayReq[PlayReq["REQ_TARGET_MIN_ATTACK"] = 41] = "REQ_TARGET_MIN_ATTACK";
    PlayReq[PlayReq["REQ_CAN_BE_TARGETED_BY_HERO_POWERS"] = 42] = "REQ_CAN_BE_TARGETED_BY_HERO_POWERS";
    PlayReq[PlayReq["REQ_ENEMY_TARGET_NOT_IMMUNE"] = 43] = "REQ_ENEMY_TARGET_NOT_IMMUNE";
    PlayReq[PlayReq["REQ_ENTIRE_ENTOURAGE_NOT_IN_PLAY"] = 44] = "REQ_ENTIRE_ENTOURAGE_NOT_IN_PLAY";
    PlayReq[PlayReq["REQ_MINIMUM_TOTAL_MINIONS"] = 45] = "REQ_MINIMUM_TOTAL_MINIONS";
    PlayReq[PlayReq["REQ_MUST_TARGET_TAUNTER"] = 46] = "REQ_MUST_TARGET_TAUNTER";
    PlayReq[PlayReq["REQ_UNDAMAGED_TARGET"] = 47] = "REQ_UNDAMAGED_TARGET";
    PlayReq[PlayReq["REQ_CAN_BE_TARGETED_BY_BATTLECRIES"] = 48] = "REQ_CAN_BE_TARGETED_BY_BATTLECRIES";
    PlayReq[PlayReq["REQ_STEADY_SHOT"] = 49] = "REQ_STEADY_SHOT";
    PlayReq[PlayReq["REQ_MINION_OR_ENEMY_HERO"] = 50] = "REQ_MINION_OR_ENEMY_HERO";
    PlayReq[PlayReq["REQ_TARGET_IF_AVAILABLE_AND_DRAGON_IN_HAND"] = 51] = "REQ_TARGET_IF_AVAILABLE_AND_DRAGON_IN_HAND";
    PlayReq[PlayReq["REQ_LEGENDARY_TARGET"] = 52] = "REQ_LEGENDARY_TARGET";
    PlayReq[PlayReq["REQ_FRIENDLY_MINION_DIED_THIS_TURN"] = 53] = "REQ_FRIENDLY_MINION_DIED_THIS_TURN";
    PlayReq[PlayReq["REQ_FRIENDLY_MINION_DIED_THIS_GAME"] = 54] = "REQ_FRIENDLY_MINION_DIED_THIS_GAME";
    PlayReq[PlayReq["REQ_ENEMY_WEAPON_EQUIPPED"] = 55] = "REQ_ENEMY_WEAPON_EQUIPPED";
    PlayReq[PlayReq["REQ_TARGET_IF_AVAILABLE_AND_MINIMUM_FRIENDLY_MINIONS"] = 56] = "REQ_TARGET_IF_AVAILABLE_AND_MINIMUM_FRIENDLY_MINIONS";
    PlayReq[PlayReq["REQ_TARGET_WITH_BATTLECRY"] = 57] = "REQ_TARGET_WITH_BATTLECRY";
    PlayReq[PlayReq["REQ_TARGET_WITH_DEATHRATTLE"] = 58] = "REQ_TARGET_WITH_DEATHRATTLE";
    PlayReq[PlayReq["REQ_TARGET_IF_AVAILABLE_AND_MINIMUM_FRIENDLY_SECRETS"] = 59] = "REQ_TARGET_IF_AVAILABLE_AND_MINIMUM_FRIENDLY_SECRETS";
    PlayReq[PlayReq["REQ_SECRET_CAP_FOR_NON_SECRET"] = 60] = "REQ_SECRET_CAP_FOR_NON_SECRET";
    PlayReq[PlayReq["REQ_TARGET_EXACT_COST"] = 61] = "REQ_TARGET_EXACT_COST";
    PlayReq[PlayReq["REQ_STEALTHED_TARGET"] = 62] = "REQ_STEALTHED_TARGET";
    PlayReq[PlayReq["REQ_MINION_SLOT_OR_MANA_CRYSTAL_SLOT"] = 63] = "REQ_MINION_SLOT_OR_MANA_CRYSTAL_SLOT";
    PlayReq[PlayReq["REQ_DRAG_TO_PLAY"] = 64] = "REQ_DRAG_TO_PLAY";
})(PlayReq || (PlayReq = {}));
var PlayState;
(function (PlayState) {
    PlayState[PlayState["INVALID"] = 0] = "INVALID";
    PlayState[PlayState["PLAYING"] = 1] = "PLAYING";
    PlayState[PlayState["WINNING"] = 2] = "WINNING";
    PlayState[PlayState["LOSING"] = 3] = "LOSING";
    PlayState[PlayState["WON"] = 4] = "WON";
    PlayState[PlayState["LOST"] = 5] = "LOST";
    PlayState[PlayState["TIED"] = 6] = "TIED";
    PlayState[PlayState["DISCONNECTED"] = 7] = "DISCONNECTED";
    PlayState[PlayState["QUIT"] = 8] = "QUIT";
    PlayState[PlayState["CONCEDED"] = 8] = "CONCEDED";
})(PlayState || (PlayState = {}));
var PowerType;
(function (PowerType) {
    PowerType[PowerType["FULL_ENTITY"] = 1] = "FULL_ENTITY";
    PowerType[PowerType["SHOW_ENTITY"] = 2] = "SHOW_ENTITY";
    PowerType[PowerType["HIDE_ENTITY"] = 3] = "HIDE_ENTITY";
    PowerType[PowerType["TAG_CHANGE"] = 4] = "TAG_CHANGE";
    PowerType[PowerType["BLOCK_START"] = 5] = "BLOCK_START";
    PowerType[PowerType["ACTION_START"] = 5] = "ACTION_START";
    PowerType[PowerType["BLOCK_END"] = 6] = "BLOCK_END";
    PowerType[PowerType["ACTION_END"] = 6] = "ACTION_END";
    PowerType[PowerType["CREATE_GAME"] = 7] = "CREATE_GAME";
    PowerType[PowerType["META_DATA"] = 8] = "META_DATA";
    PowerType[PowerType["CHANGE_ENTITY"] = 9] = "CHANGE_ENTITY";
})(PowerType || (PowerType = {}));
var Race;
(function (Race) {
    Race[Race["INVALID"] = 0] = "INVALID";
    Race[Race["BLOODELF"] = 1] = "BLOODELF";
    Race[Race["DRAENEI"] = 2] = "DRAENEI";
    Race[Race["DWARF"] = 3] = "DWARF";
    Race[Race["GNOME"] = 4] = "GNOME";
    Race[Race["GOBLIN"] = 5] = "GOBLIN";
    Race[Race["HUMAN"] = 6] = "HUMAN";
    Race[Race["NIGHTELF"] = 7] = "NIGHTELF";
    Race[Race["ORC"] = 8] = "ORC";
    Race[Race["TAUREN"] = 9] = "TAUREN";
    Race[Race["TROLL"] = 10] = "TROLL";
    Race[Race["UNDEAD"] = 11] = "UNDEAD";
    Race[Race["WORGEN"] = 12] = "WORGEN";
    Race[Race["GOBLIN2"] = 13] = "GOBLIN2";
    Race[Race["MURLOC"] = 14] = "MURLOC";
    Race[Race["DEMON"] = 15] = "DEMON";
    Race[Race["SCOURGE"] = 16] = "SCOURGE";
    Race[Race["MECHANICAL"] = 17] = "MECHANICAL";
    Race[Race["ELEMENTAL"] = 18] = "ELEMENTAL";
    Race[Race["OGRE"] = 19] = "OGRE";
    Race[Race["PET"] = 20] = "PET";
    Race[Race["BEAST"] = 20] = "BEAST";
    Race[Race["TOTEM"] = 21] = "TOTEM";
    Race[Race["NERUBIAN"] = 22] = "NERUBIAN";
    Race[Race["PIRATE"] = 23] = "PIRATE";
    Race[Race["DRAGON"] = 24] = "DRAGON";
})(Race || (Race = {}));
var Rarity;
(function (Rarity) {
    Rarity[Rarity["INVALID"] = 0] = "INVALID";
    Rarity[Rarity["COMMON"] = 1] = "COMMON";
    Rarity[Rarity["FREE"] = 2] = "FREE";
    Rarity[Rarity["RARE"] = 3] = "RARE";
    Rarity[Rarity["EPIC"] = 4] = "EPIC";
    Rarity[Rarity["LEGENDARY"] = 5] = "LEGENDARY";
    Rarity[Rarity["UNKNOWN_6"] = 6] = "UNKNOWN_6";
})(Rarity || (Rarity = {}));
var State;
(function (State) {
    State[State["INVALID"] = 0] = "INVALID";
    State[State["LOADING"] = 1] = "LOADING";
    State[State["RUNNING"] = 2] = "RUNNING";
    State[State["COMPLETE"] = 3] = "COMPLETE";
})(State || (State = {}));
var Step;
(function (Step) {
    Step[Step["INVALID"] = 0] = "INVALID";
    Step[Step["BEGIN_FIRST"] = 1] = "BEGIN_FIRST";
    Step[Step["BEGIN_SHUFFLE"] = 2] = "BEGIN_SHUFFLE";
    Step[Step["BEGIN_DRAW"] = 3] = "BEGIN_DRAW";
    Step[Step["BEGIN_MULLIGAN"] = 4] = "BEGIN_MULLIGAN";
    Step[Step["MAIN_BEGIN"] = 5] = "MAIN_BEGIN";
    Step[Step["MAIN_READY"] = 6] = "MAIN_READY";
    Step[Step["MAIN_RESOURCE"] = 7] = "MAIN_RESOURCE";
    Step[Step["MAIN_DRAW"] = 8] = "MAIN_DRAW";
    Step[Step["MAIN_START"] = 9] = "MAIN_START";
    Step[Step["MAIN_ACTION"] = 10] = "MAIN_ACTION";
    Step[Step["MAIN_COMBAT"] = 11] = "MAIN_COMBAT";
    Step[Step["MAIN_END"] = 12] = "MAIN_END";
    Step[Step["MAIN_NEXT"] = 13] = "MAIN_NEXT";
    Step[Step["FINAL_WRAPUP"] = 14] = "FINAL_WRAPUP";
    Step[Step["FINAL_GAMEOVER"] = 15] = "FINAL_GAMEOVER";
    Step[Step["MAIN_CLEANUP"] = 16] = "MAIN_CLEANUP";
    Step[Step["MAIN_START_TRIGGERS"] = 17] = "MAIN_START_TRIGGERS";
})(Step || (Step = {}));
var Type;
(function (Type) {
    Type[Type["LOCSTRING"] = -2] = "LOCSTRING";
    Type[Type["UNKNOWN"] = 0] = "UNKNOWN";
    Type[Type["BOOL"] = 1] = "BOOL";
    Type[Type["NUMBER"] = 2] = "NUMBER";
    Type[Type["COUNTER"] = 3] = "COUNTER";
    Type[Type["ENTITY"] = 4] = "ENTITY";
    Type[Type["PLAYER"] = 5] = "PLAYER";
    Type[Type["TEAM"] = 6] = "TEAM";
    Type[Type["ENTITY_DEFINITION"] = 7] = "ENTITY_DEFINITION";
    Type[Type["STRING"] = 8] = "STRING";
})(Type || (Type = {}));
var Zone;
(function (Zone) {
    Zone[Zone["DISCARD"] = -2] = "DISCARD";
    Zone[Zone["INVALID"] = 0] = "INVALID";
    Zone[Zone["PLAY"] = 1] = "PLAY";
    Zone[Zone["DECK"] = 2] = "DECK";
    Zone[Zone["HAND"] = 3] = "HAND";
    Zone[Zone["GRAVEYARD"] = 4] = "GRAVEYARD";
    Zone[Zone["REMOVEDFROMGAME"] = 5] = "REMOVEDFROMGAME";
    Zone[Zone["SETASIDE"] = 6] = "SETASIDE";
    Zone[Zone["SECRET"] = 7] = "SECRET";
})(Zone || (Zone = {}));
//# sourceMappingURL=card.js.map